package com.carsnet.utils

class CarsContainer {
  static final def FEATURED = [
      'audi',
      'bmw',
      'honda',
      'hyundai',
      'mazda',
      'mercedes',
      'mitsubishi',
      'opel',
      'skoda',
      'toyota'
  ]

  static final def CARS = [
      'abarth',
      'alfa romeo',
      'alpina',
      'alpine',
      'aro',
      'asia',
      'aston martin',
      'audi',
      'bentley',
      'bmw',
      'brilliance',
      'bugatti',
      'buick',
      'cadillac',
      'caterham',
      'chevrolet',
      'chrysler',
      'citroen',
      'corvette',
      'dacia',
      'daewoo',
      'daihatsu',
      'daimler',
      'de tomaso',
      'dodge',
      'donkervoort',
      'dragon',
      'ferrari',
      'fiat',
      'ford',
      'galloper',
      'honda',
      'hummer',
      'hyundai',
      'infiniti',
      'isuzu',
      'iveco',
      'jaguar',
      'jeep',
      'jonway',
      'kia',
      'lada',
      'lamborghini',
      'lancia',
      'land rover',
      'landwind',
      'lexus',
      'lotus',
      'mahindra',
      'maserati',
      'maybach',
      'mazda',
      'mclaren',
      'mercedes',
      'mg',
      'mini',
      'mitsubishi',
      'morgan',
      'nissan',
      'opel',
      'peugeot',
      'pontiac',
      'porsche',
      'proton',
      'renault',
      'rolls-royce',
      'rover',
      'saab',
      'seat',
      'shuanghuan',
      'skoda',
      'smart',
      'ssangyong',
      'subaru',
      'suzuki',
      'wiesmann',
      'toyota',
      'tvr',
      'volkswagen',
      'volvo'
  ]
}
