INSERT INTO car_brands (name, image, featured) VALUES ('abarth', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('alfa romeo', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('alpina', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('alpine', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('aro', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('asia', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('aston martin', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('audi', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('bentley', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('bmw', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('brilliance', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('bugatti', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('buick', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('cadillac', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('caterham', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('chevrolet', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('chrysler', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('citroen', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('corvette', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('dacia', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('daewoo', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('daihatsu', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('daimler', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('de tomaso', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('dodge', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('donkervoort', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('dragon', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('ferrari', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('fiat', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('ford', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('galloper', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('honda', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('hummer', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('hyundai', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('infiniti', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('isuzu', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('iveco', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('jaguar', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('jeep', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('jonway', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('kia', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('lada', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('lamborghini', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('lancia', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('land rover', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('landwind', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('lexus', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('lotus', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mahindra', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('maserati', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('maybach', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mazda', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mclaren', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mercedes', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mg', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mini', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('mitsubishi', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('morgan', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('nissan', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('opel', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('peugeot', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('pontiac', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('porsche', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('proton', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('renault', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('rolls-royce', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('rover', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('saab', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('seat', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('shuanghuan', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('skoda', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('smart', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('ssangyong', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('subaru', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('suzuki', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('wiesmann', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('toyota', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('tvr', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('volkswagen', NULL, false);
INSERT INTO car_brands (name, image, featured) VALUES ('volvo', NULL, false);

INSERT INTO car_models (name, brand_id) VALUES ('3000 GT', 57);
INSERT INTO car_models (name, brand_id) VALUES ('ASX', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Carisma', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Colt', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Eclipse', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Galant', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Grandis', 57);
INSERT INTO car_models (name, brand_id) VALUES ('I', 57);
INSERT INTO car_models (name, brand_id) VALUES ('L300', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Lancer', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Outlander', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Pajero', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Pajero Classic', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Pajero Pini', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Pajero Sport', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Sigma', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Space Gear', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Space Runner', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Space Star', 57);
INSERT INTO car_models (name, brand_id) VALUES ('Space Wagon', 57);


INSERT INTO car_models (name, brand_id) VALUES ('Carens', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Carnival', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Cee''d', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Cerato', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Clarus', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Joice', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Magentis', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Opirus', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Picanto', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Pride', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Retona', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Rio', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Rio II', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Roadster', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Sephia', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Shuma', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Sorento', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Soul', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Sportage', 41);
INSERT INTO car_models (name, brand_id) VALUES ('Venga', 41);
